version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  pre_build:
    commands:
      - apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
      - apt-get update -y
      - apt-get -y install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - npx cypress --version
  build:
    commands:
      - npm run cypress:run:stag
